site_name: AB's Cloud SOC Wiki
site_url: https://cloudsoc.example
theme:
  icon:
    logo: material/cloud-outline
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
  name: material
  font:
    text: Roboto
  palette:
    scheme: slate
    primary: blue


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/axel-banks-3b7712105/

copyright: Copyright &copy; 2025 Axel Banks